"""
Django settings for super_worm project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import codecs

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# if encode error utf8mb4  use this
codecs.register(lambda name: codecs.lookup('utf8') if name == 'utf8mb4' else None)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '94(%%3un8vtf3=u-b3gm%0r!!h3(j#e01rfmo#b$+=bg6w3o#('
SHUJUBAO_GOLD_KEY = 'ce42c2c5418a5cb266657b25f9067965'
SHUJUBAO_SILVER_KEY = '12916b979f23b5f51b997c9f1d0c1da4'
ALIYUN_STOCK_APP_CODE = 'eeb79d47f0604f5bb403d9318368f21b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

MONGO_HOST = 'dds-m5ea0fc94e106de42.mongodb.rds.aliyuncs.com'
MONGO_PORT = 3717
MONGO_DATABASE = 'finance'
MONGO_USERNAME = 'root'
MONGO_PASSWORD = '1234qwer'

ALLOWED_HOSTS = []
COMPRESS_ENABLED = True
# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_crontab',
    'gunicorn',
    'web',
    'finance'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, '/static'),
STATIC_ROOT = os.path.join(BASE_DIR, 'static/','static/tradingview/charting_librarystatic/')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static/"),
    os.path.join(BASE_DIR, "static/tradingview/charting_librarystatic/"),
)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

ROOT_URLCONF = 'super_worm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'super_worm.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'super_worm',
        'USER': 'robot',
        'PASSWORD': '1234qwer!@#',
        'HOST': 'rm-2ze283n193y53a907.mysql.rds.aliyuncs.com',
        'PORT': 3306,
        'OPTIONS': {'charset': 'utf8mb4'}
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'super_worm',
#         'USER': 'root',
#         'PASSWORD': '1234qwer',
#         'HOST': '127.0.0.1',
#         'PORT': 3306,
#         'OPTIONS': {'charset': 'utf8mb4'}
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/
ugettext = lambda s: s
LANGUAGES = [
    ('zh', ugettext('Chinese')),
    ('zh_CN', ugettext('Chinese')),
    ('en', ugettext('English')),
]

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

CRONTAB_LOCK_JOBS = False

CRONTAB_DJANGO_MANAGE_PATH = '/home/django-scrapy/manage_production.py'
CRONJOBS = [
    ('*/9  * * * *', 'web.tasks.get_yuncaijing_insider', '>> /var/log/super_worm/get_yuncaijing_insider.log'),
    ('*/10  * * * *', 'web.tasks.get_guzhang', '>> /var/log/super_worm/get_guzhang.log'),
    ('*/15  * * * *', 'web.tasks.get_finance_brief', '>> /var/log/super_worm/get_finance_brief.log'),
    ('0 0 * * *', 'web.tasks.get_stack_code', '>> /var/log/super_worm/get_stack_code.log'),
    ('0 0 * * *', 'web.tasks.get_k_datas', '>> /var/log/super_worm/get_k_datas.log'),

]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
        },
        'websocket': {
            'format': '%(asctime)s %(process)d:%(name)s %(levelname)s: %(message)s'
        }
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.getenv('TEMP') if (os.name == 'nt') else '/var/log/super_worm', 'super_worm.log'),
            'maxBytes': 1024 * 1024 * 20,
            'backupCount': 20,
            'formatter': 'verbose'
        },
        'cron_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.getenv('TEMP') if (os.name == 'nt') else '/var/log/super_worm', 'django_crontab.log'),
            'maxBytes': 1024 * 1024 * 20,
            'backupCount': 20,
            'formatter': 'verbose'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
        },
        'django_crontab': {
            'handlers': ['cron_file'],
            'level': 'INFO',
        }
    }
}
